name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Cloudflare Pages
      url: https://cv.d-rose.io
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: dist
          path: dist
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 38d5d89bcdaf995293ada66caafe9428
          command: pages deploy dist --project-name=cv